[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.project_version }}"
description = "{{ cookiecutter.project_short_description }}"
authors = [
    "{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>",
]
license = "{{ cookiecutter.open_source_license }}"
readme = "README.md"
homepage = ""
repository = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_repository_name }}"
documentation = "https://{{ cookiecutter.project_slug }}.readthedocs.org/en/latest/"
keywords = []
classifiers = [
    # "License :: OSI Approved :: {{ cookiecutter.open_source_license }}",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

# Requirements
[tool.poetry.dependencies]
python = "^3.4"
typing = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "~3.4"
pytest-cov = "~2.5"
pytest-mock = "~1.9"
detox = "*"
sphinx = "*"
sphinx-autobuild = "*"
sphinx_rtd_theme = "*"
sphinxcontrib-apidoc = "*"
black = { version = "^18.3-alpha.0", python = "^3.6" }
yapf = "*"
flake8 = "*"
isort = "*"
bandit = "*"
mypy = { version = "*", optional = true }

[tool.poetry.extras]
mypy = ["mypy"]

[tool.black]
line-length = 100
