language: python

python:
  - 3.6
  - pypy3

install:
  - pip install cookiecutter
  - pip install detox

script:
  - detox -vv

after_success:
  - yes '' | cookiecutter .

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: fresh_baked_skeleton
  repo: Curly-Mo/fresh-baked-skeleton
  target-branch: master
  verbose: true
  on:
    branch: master
