language: python

python:
  - 3.7

install:
  - pip install cookiecutter
  - pip install tox

script:
  - tox -vv

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  - yes '' | cookiecutter .
  - pip install poetry
  - cd fresh_baked_skeleton
  - poetry version 0.1.${TRAVIS_BUILD_NUMBER}

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: fresh_baked_skeleton
  repo: Curly-Mo/fresh-baked-skeleton
  target-branch: master
  verbose: true
  on:
    branch: master
