language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - pypy3

install:
  - pip install cookiecutter
  - pip install tox-travis

script:
  - tox

notifications:
  email:
    on_success: change
    on_failure: change
