language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
  # - pypy3.6

install:
  - pip install pipenv cookiecutter
  - pip install tox-travis

script:
  - tox

notifications:
  email:
    on_success: change
    on_failure: change
